version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: androidtv-remote-backend
    restart: unless-stopped
    ports:
      - "7432:7432"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=src/app.py
      - BACKEND_PORT=${BACKEND_PORT:-7432}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:7432}
    networks:
      - androidtv-network

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: androidtv-remote-frontend
    restart: unless-stopped
    ports:
      - "7433:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://localhost:7432}
    networks:
      - androidtv-network

# Define a network for the services
networks:
  androidtv-network:
    driver: bridge

# Define volumes for persistent data
volumes:
  paired_tvs_data:
    driver: local